[package]
name = "paseto"
description = "An alternative token format to JWT"
version = "1.0.4"
license = "MIT"
authors = [
  "Cynthia Coan <ccoan@instructure.com>"
]
edition = "2018"

[features]
default = ["v1", "v2", "easy_tokens"]
v1 = ["openssl"]
v2 = ["sodiumoxide"]
easy_tokens = ["serde_json", "chrono"]

[dependencies]
base64 = "^0.10"
chrono = { version = "^0.4", optional = true, features = ["serde"] }
failure = "^0.1"
failure_derive = "^0.1"
openssl = { version = "~0.10.20", optional = true }
ring = "0.16.0"
serde_json = { version = "^1.0.0", optional = true }
sodiumoxide = { version = "^0.2.1", optional = true }

[dev-dependencies]
hex = "^0.3.2"
