name: Build/Test

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron: '0 0 * * *'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: cargo build --all --verbose
    - name: Run tests
      run: cargo test --all --verbose
  test-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Install rust
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Build
      run: (source $HOME/.cargo/env && cargo build --all --verbose)
    - name: Run tests
      run: (source $HOME/.cargo/env && cargo test --all --verbose)
